apiVersion: v1
kind: PersistentVolumeClaim  # 1 
metadata:
    name: example-pv-claim  # 2
    labels:
      app: example-application  # 3
spec:
  accessModes:   
    - ReadWriteOnce # 4
  resources:
    requests:
      storage: 25Gi   # 5


---
# 1 => This part Indicates that it is a persistent volume claim
#
# 2 => Indicates The name to use in the claimName field of the persistentVolumeClaim element in the
#       volumes section of a deployment manifest.
#
# 3 => Indicates the label to be associated to the pvc 

# 4 =>  Indicates the access mode given to this pvc
#
# 5 => The storage class will create a persistent volume matching this size request. 
#
#
#
#
#
#
